### PR TITLE
Carthage Support

### PR DESCRIPTION
**Pull request by chrisdhaan**
- Added Carthage support #1 

@hawk-ukr please review changes. 

I apologize for the large number of files changed. While this may seem odd at first if you scroll through you'll notice I actually didn't change much. I updated the APValidators library using CocoaPods newest ```pod lib create ****``` command available with CocoaPods 1.1.1. They also suggest a .gitignore setup slightly different from the one you had previously. This pushed the .xcworkspace along with the Pods directory to the repo. Most of the files changes are these additions. You'll see I also updated the README.md to reflect installing via Carthage. I bumped the version in the .podspec but did not push a tag for release. I figured I'd leave that up to you.

Let me know if you see any issues with the way I went about doing this but the Carthage installation does work. You can create a Cartfile and add ```"chrisdhaan/APValidators" "carthage-support"``` to test it.

### CODE REVIEW

**Comment by chrisdhaan** [comment]
It looks like the continuous integration failed for this branch. Is there any way the failing output could be pasted here so I can fix it?

**Comment by NickolaySheika** [comment]
Hey @chrisdhaan, thank you for your contribution. And sorry for my late response.

I see that CI cannot compile tests target. And I know why - you've missed the target for tests .m files. 

Also, about adding `Pods` folder to Git. I don't prefer this approach. You can read about pros and cons here - http://guides.cocoapods.org/using/using-cocoapods.html#should-i-ignore-the-pods-directory-in-source-control So I think we should get back to the previous variant of `.gitignore` and removing `Pods` from Git.

What do you think?

**Comment by chrisdhaan** [comment]
@hawk-ukr no worries on the late response.

Can you elaborate on "I missed the target for tests .m files? I didn't think I had touched anything regarding the tests.

No worries about not storing Pods in git. I'll remove that.

**Comment by NickolaySheika** [comment]
@chrisdhaan all test .m files added to main target, not in tests target

**Comment by chrisdhaan** [comment]
@hawk-ukr I removed most of the files from the Pods directory. Anything related to OCMock and Expecta have been removed. I also added the .m files back to the Test target but there still seems to be something failing. If you can update me on what it is I'll continue to fix the issue.

The reason I couldn't remove the whole Pods directory is because Carthage relies on parts of it to build the scheme for the framework. I don't know how else to make Carthage installation work without the Pods/APValidator files being there.

**Comment by chrisdhaan** [comment]
@hawk-ukr I can cancel this PR and delete my fork if you aren't interested in this anymore.

**Pull request closed without merging**
